name: laravel-app
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: mhammadgammal/job-backoffice
      branch: main
      deploy_on_push: true
    http_port: 80
    health_check:
      http_path: /
    instance_count: 1
    instance_size_slug: basic-xxs
# Optional: Add a managed database
# databases:
#   - name: db
#     engine: MYSQL
#     version: "8"
#     production: false
#     cluster_name: laravel-db-cluster
# Optional: Add Redis for caching/sessions
# databases:
#   - name: redis
#     engine: REDIS
#     version: "7"
#     production: false
# Optional: Static site for serving assets (if not served by Laravel)
# static_sites:
#   - name: assets
#     source_dir: public
#     output_dir: /
#     routes:
#       - path: /assets
